import { defineSuite } from "../helpers/suite";

// TODO: The aslan-fib.jam.wat was generated by the aslan compiler with a different ABI
// (JAM-style single-param entry points returning i32). It needs to be regenerated
// with the new unified i64 return convention (packed ptr+len).
defineSuite({
  name: "aslan-fib",
  skipPvmInPvm: true,
  tests: [],
});
