#!/usr/bin/env bash
# Walk every decompressed runtime under ./wasm/ and produce a per-runtime
# audit of *every* f32/f64 operator location: the containing function (idx
# and a best-effort demangled name) plus the WASM op kind. Output goes to
# ./floats/<runtime>.{tsv,md}.
#
# `compile.sh` populates ./wasm/ — run it first if the directory is empty.

set -euo pipefail

THIS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WASM_DIR="$THIS_DIR/wasm"
OUT_DIR="$THIS_DIR/floats"

mkdir -p "$OUT_DIR"

if ! command -v wasm-tools >/dev/null 2>&1; then
  echo "wasm-tools is required (cargo install wasm-tools)" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required" >&2
  exit 1
fi

shopt -s nullglob
WASMS=("$WASM_DIR"/*.wasm)
shopt -u nullglob

if [ ${#WASMS[@]} -eq 0 ]; then
  echo "No WASM files in $WASM_DIR. Run ./compile.sh first to download/decompress." >&2
  exit 1
fi

audit_one() {
  local wasm="$1"
  local short="$2"
  local tsv="$OUT_DIR/$short.tsv"
  local md="$OUT_DIR/$short.md"

  echo "Auditing $short ..." >&2
  wasm-tools print "$wasm" 2>/dev/null \
    | python3 "$THIS_DIR/_audit-floats.py" "$short" "$tsv" "$md"
}

for wasm in "${WASMS[@]}"; do
  short="$(basename "$wasm" .wasm)"
  audit_one "$wasm" "$short"
done

# ----------------------------------------------------------------------------
# Render combined summary
# ----------------------------------------------------------------------------

INDEX="$OUT_DIR/README.md"
{
  echo "# Float-op audit — polkadot-fellows runtimes"
  echo
  echo "Per-runtime breakdown of every f32/f64 operator site in the decompressed runtimes under \`../wasm/\`. Generated by \`./audit-floats.sh\`. Each runtime has a \`<runtime>.md\` summary (function-level rollup) and a \`<runtime>.tsv\` raw record-per-occurrence dump for further filtering."
  echo
  echo "| Runtime | Float ops | Functions touching floats | Detail |"
  echo "|---------|----------:|--------------------------:|--------|"
  for wasm in "${WASMS[@]}"; do
    short="$(basename "$wasm" .wasm)"
    md="$OUT_DIR/$short.md"
    tsv="$OUT_DIR/$short.tsv"
    [ -f "$tsv" ] || continue
    occurrences=$(($(wc -l < "$tsv") - 1))
    fns=$(awk -F'\t' 'NR>1 {print $1"\t"$4}' "$tsv" | sort -u | wc -l | tr -d ' ')
    printf '| %s | %d | %s | [%s.md](%s.md) |\n' "$short" "$occurrences" "$fns" "$short" "$short"
  done
  echo
  echo "## Non-\`serde_json\` float users"
  echo
  echo "Most float ops in these runtimes come from \`serde_json\`'s number deserialization (\`f64_from_parts\`, \`parse_integer\`, \`parse_exponent_overflow\`, \`ParserNumber::invalid_type\`, \`deserialize_u32\`/etc.) — present because the WASM exports \`GenesisBuilder_get_preset\` and similar JSON-consuming runtime APIs, but cold-path during normal block execution. The functions below are the *non*-\`serde_json\` float users — i.e. genuine runtime code paths that would trap if they ran under \`--trap-floats\`."
  echo
  echo "| Runtime | Function | Ops |"
  echo "|---------|----------|----:|"
  for wasm in "${WASMS[@]}"; do
    short="$(basename "$wasm" .wasm)"
    tsv="$OUT_DIR/$short.tsv"
    [ -f "$tsv" ] || continue
    # Aggregate (fn_idx, name) → count, exclude rows whose name contains
    # "serde_", "DeserializeSeed", or "PhantomData" — the JSON deserialization
    # plumbing.
    awk -F'\t' -v rt="$short" '
      NR == 1 { next }
      $4 ~ /serde/ || $4 ~ /DeserializeSeed/ || $4 ~ /PhantomData/ { next }
      { count[$1 "\t" $4]++ }
      END {
        for (k in count) {
          split(k, a, "\t")
          printf "%s\t%s\t%s\t%d\n", rt, a[1], a[2], count[k]
        }
      }
    ' "$tsv"
  done | sort -t$'\t' -k4,4nr -k1,1 | while IFS=$'\t' read -r rt fidx fname cnt; do
    [ -n "$fname" ] || continue
    safe_name="${fname//|/\\|}"
    printf '| %s | `%s` | %d |\n' "$rt" "$safe_name" "$cnt"
  done
  echo
  echo "If a runtime is absent from this table, all of its float ops are inside \`serde_json\` paths."
} > "$INDEX"

echo "Wrote audit to $OUT_DIR/" >&2
echo "Index: $INDEX" >&2
